### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by UnknownNull** [Sergittos/BedWars#2]
```
2024-01-02 [19:54:54.065] [Server thread/CRITICAL]: pocketmine\thread\ThreadCrashException: "Worker 2 crashed while running task sergittos\bedwars\game\task\GenerateGameTask#63459" (EXCEPTION) in "pmsrc/src/scheduler/AsyncPool" at line 226
--- Stack trace ---
  #0 pmsrc/src/scheduler/AsyncPool(266): pocketmine\scheduler\AsyncPool->checkCrashedWorker(int 2, object sergittos\bedwars\game\task\GenerateGameTask#63459)
  #1 pmsrc/src/scheduler/AsyncPool(241): pocketmine\scheduler\AsyncPool->collectTasksFromWorker(int 2)
  #2 pmsrc/src/Server(1829): pocketmine\scheduler\AsyncPool->collectTasks()
  #3 pmsrc/src/Server(1714): pocketmine\Server->tick()
  #4 pmsrc/src/Server(1090): pocketmine\Server->tickProcessor()
  #5 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[39] E:\minecraft pe server\server pm5 test\, string[47] E:\minecraft pe server\server pm5 test\plugins\)
  #6 pmsrc/src/PocketMine(364): pocketmine\server()
  #7 pmsrc(11): require(string[83] phar://E:/minecraft pe server/server pm5 test/PocketMine-MP.phar/src/PocketMine.)
```

**Comment by UnknownNull** [comment]
When the server is turned on, the server crashes.

To better understand this issue, delete your plugin data once and familiarize yourself with the problems of your plugin during startup.
@Sergittos

**Comment by Sergittos** [comment]
Delete your ``maps.json`` file and try again with the updated version on GitHub.

**Comment by UnknownNull** [comment]
> Delete your `maps.json` file and try again with the updated version on GitHub.

Error: "Class "EasyUI\variant\SimpleForm" not found" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/form/SimpleForm" at line 15

**Comment by UnknownNull** [comment]
```
name: libEasyUI
author: GiantQuartz
api: 4.0.0
version: 1.0.2
antigen: EasyUI
```

true?

**Comment by UnknownNull** [comment]
oh no wait...

**Comment by UnknownNull** [comment]
Class "FormResponse" does not exist in "libEasyUI".
![image](https://github.com/Sergittos/BedWars/assets/91208232/77536369-2d4c-4502-af43-2344716421c4)

**Comment by UnknownNull** [comment]
after select map and submit:

![image](https://github.com/Sergittos/BedWars/assets/91208232/2b6d0c41-c35b-496d-bea6-94ff03a55f10)
```
        if($name === "") {
            $player->sendMessage(TextFormat::RED . "You must set a name!");
            return;
```

**Comment by Sergittos** [comment]
That's because you haven't set a name

**Comment by UnknownNull** [comment]
> That's because you haven't set a name

![image](https://github.com/Sergittos/BedWars/assets/91208232/e4b547b8-3504-4c96-95aa-c1fa6ea82c51)

**Comment by Sergittos** [comment]
Scroll down and then up and it will display the option to set the name

**Comment by UnknownNull** [comment]
> Scroll down and then up and it will display the option to set the name

![image](https://github.com/Sergittos/BedWars/assets/91208232/4dc16ff7-77c9-46ad-9cd3-907982fa1f77)
I set a map with 2 teams, but it asks me to set up all teams and does not allow me to complete the process.

**Comment by UnknownNull** [comment]
and after kill player:
```
[Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 63
--- Stack trace ---
  #0 pmsrc/src/entity/Entity(1445): pocketmine\world\Position->getWorld()
  #1 pmsrc/src/player/Player(2547): pocketmine\entity\Entity->teleport(object pocketmine\world\Position#216311, null, null)
  #2 plugins/BedWars-master/src/sergittos/bedwars/session/Session(368): pocketmine\player\Player->teleport(object pocketmine\world\Position#216311)
  #3 plugins/BedWars-master/src/sergittos/bedwars/listener/GameListener(85): sergittos\bedwars\session\Session->kill(int 1)
  #4 pmsrc/src/event/RegisteredListener(61): sergittos\bedwars\listener\GameListener->onReceiveDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
  #5 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
  #6 pmsrc/src/entity/Entity(532): pocketmine\event\Event->call()
  #7 pmsrc/src/entity/Living(557): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
  #8 pmsrc/src/player/Player(2468): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
  #9 pmsrc/src/player/Player(1869): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
  #10 pmsrc/src/network/mcpe/handler/InGamePacketHandler(560): pocketmine\player\Player->attackEntity(object pocketmine\player\Player#272225)
  #11 pmsrc/src/network/mcpe/handler/InGamePacketHandler(347): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network
```

and restart server crash:
```
2024-01-04 [17:27:54.936] [Server thread/CRITICAL]: ErrorException: "foreach() argument must be of type array|object, null given" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/game/map/MapFactory" at line 32
--- Stack trace ---
  #0 plugins/BedWars-master/src/sergittos/bedwars/game/map/MapFactory(32): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[59] foreach() argument must be of type array|object, null given, string[107] E:\minecraft pe server\server pm5 test\plugins\BedWars-master\src\sergittos\bedw, int 32)
  #1 plugins/BedWars-master/src/sergittos/bedwars/BedWars(55): sergittos\bedwars\game\map\MapFactory::init()
  #2 pmsrc/src/plugin/PluginBase(119): sergittos\bedwars\BedWars->onEnable()
  #3 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #4 pmsrc/src/Server(1424): pocketmine\plugin\PluginManager->enablePlugin(object sergittos\bedwars\BedWars#45685)
  #5 pmsrc/src/Server(1059): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#45423)
  #6 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[39] E:\minecraft pe server\server pm5 test\, string[47] E:\minecraft pe server\server pm5 test\plugins\)
  #7 pmsrc/src/PocketMine(364): pocketmine\server()
  #8 pmsrc(11): require(string[83] phar://E:/minecraft pe server/server pm5 test/PocketMine-MP.phar/src/PocketMine.)
```

**Comment by Sergittos** [comment]
> and after kill player:
> ```
> [Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 63
> --- Stack trace ---
>   #0 pmsrc/src/entity/Entity(1445): pocketmine\world\Position->getWorld()
>   #1 pmsrc/src/player/Player(2547): pocketmine\entity\Entity->teleport(object pocketmine\world\Position#216311, null, null)
>   #2 plugins/BedWars-master/src/sergittos/bedwars/session/Session(368): pocketmine\player\Player->teleport(object pocketmine\world\Position#216311)
>   #3 plugins/BedWars-master/src/sergittos/bedwars/listener/GameListener(85): sergittos\bedwars\session\Session->kill(int 1)
>   #4 pmsrc/src/event/RegisteredListener(61): sergittos\bedwars\listener\GameListener->onReceiveDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
>   #5 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
>   #6 pmsrc/src/entity/Entity(532): pocketmine\event\Event->call()
>   #7 pmsrc/src/entity/Living(557): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
>   #8 pmsrc/src/player/Player(2468): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
>   #9 pmsrc/src/player/Player(1869): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
>   #10 pmsrc/src/network/mcpe/handler/InGamePacketHandler(560): pocketmine\player\Player->attackEntity(object pocketmine\player\Player#272225)
>   #11 pmsrc/src/network/mcpe/handler/InGamePacketHandler(347): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network
> ```
> 
> and restart server crash:
> ```
> 2024-01-04 [17:27:54.936] [Server thread/CRITICAL]: ErrorException: "foreach() argument must be of type array|object, null given" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/game/map/MapFactory" at line 32
> --- Stack trace ---
>   #0 plugins/BedWars-master/src/sergittos/bedwars/game/map/MapFactory(32): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[59] foreach() argument must be of type array|object, null given, string[107] E:\minecraft pe server\server pm5 test\plugins\BedWars-master\src\sergittos\bedw, int 32)
>   #1 plugins/BedWars-master/src/sergittos/bedwars/BedWars(55): sergittos\bedwars\game\map\MapFactory::init()
>   #2 pmsrc/src/plugin/PluginBase(119): sergittos\bedwars\BedWars->onEnable()
>   #3 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
>   #4 pmsrc/src/Server(1424): pocketmine\plugin\PluginManager->enablePlugin(object sergittos\bedwars\BedWars#45685)
>   #5 pmsrc/src/Server(1059): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#45423)
>   #6 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[39] E:\minecraft pe server\server pm5 test\, string[47] E:\minecraft pe server\server pm5 test\plugins\)
>   #7 pmsrc/src/PocketMine(364): pocketmine\server()
>   #8 pmsrc(11): require(string[83] phar://E:/minecraft pe server/server pm5 test/PocketMine-MP.phar/src/PocketMine.)
> ```

Can you show me your ``maps.json`` file?

**Comment by UnknownNull** [comment]
> > and after kill player:
> > ```
> > [Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 63
> > --- Stack trace ---
> >   #0 pmsrc/src/entity/Entity(1445): pocketmine\world\Position->getWorld()
> >   #1 pmsrc/src/player/Player(2547): pocketmine\entity\Entity->teleport(object pocketmine\world\Position#216311, null, null)
> >   #2 plugins/BedWars-master/src/sergittos/bedwars/session/Session(368): pocketmine\player\Player->teleport(object pocketmine\world\Position#216311)
> >   #3 plugins/BedWars-master/src/sergittos/bedwars/listener/GameListener(85): sergittos\bedwars\session\Session->kill(int 1)
> >   #4 pmsrc/src/event/RegisteredListener(61): sergittos\bedwars\listener\GameListener->onReceiveDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
> >   #5 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
> >   #6 pmsrc/src/entity/Entity(532): pocketmine\event\Event->call()
> >   #7 pmsrc/src/entity/Living(557): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
> >   #8 pmsrc/src/player/Player(2468): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
> >   #9 pmsrc/src/player/Player(1869): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#213671)
> >   #10 pmsrc/src/network/mcpe/handler/InGamePacketHandler(560): pocketmine\player\Player->attackEntity(object pocketmine\player\Player#272225)
> >   #11 pmsrc/src/network/mcpe/handler/InGamePacketHandler(347): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and restart server crash:
> > ```
> > 2024-01-04 [17:27:54.936] [Server thread/CRITICAL]: ErrorException: "foreach() argument must be of type array|object, null given" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/game/map/MapFactory" at line 32
> > --- Stack trace ---
> >   #0 plugins/BedWars-master/src/sergittos/bedwars/game/map/MapFactory(32): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[59] foreach() argument must be of type array|object, null given, string[107] E:\minecraft pe server\server pm5 test\plugins\BedWars-master\src\sergittos\bedw, int 32)
> >   #1 plugins/BedWars-master/src/sergittos/bedwars/BedWars(55): sergittos\bedwars\game\map\MapFactory::init()
> >   #2 pmsrc/src/plugin/PluginBase(119): sergittos\bedwars\BedWars->onEnable()
> >   #3 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
> >   #4 pmsrc/src/Server(1424): pocketmine\plugin\PluginManager->enablePlugin(object sergittos\bedwars\BedWars#45685)
> >   #5 pmsrc/src/Server(1059): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#45423)
> >   #6 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[39] E:\minecraft pe server\server pm5 test\, string[47] E:\minecraft pe server\server pm5 test\plugins\)
> >   #7 pmsrc/src/PocketMine(364): pocketmine\server()
> >   #8 pmsrc(11): require(string[83] phar://E:/minecraft pe server/server pm5 test/PocketMine-MP.phar/src/PocketMine.)
> > ```
> 
> Can you show me your `maps.json` file?
[maps.json](https://github.com/Sergittos/BedWars/files/13833886/maps.json)
I changed it to have only 2 teams, blue and red, but there was a problem!

**Comment by Sergittos** [comment]
You can't make comments on a JSON file

**Comment by Sergittos** [comment]
Everything should be fixed now

**Comment by UnknownNull** [comment]
> Everything should be fixed now

Error: Class sergittos\bedwars\game\shop\tracker\TrackerProduct contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (sergittos\bedwars\game\shop\Product::canBePurchased)
File: plugins/BedWars-master/src/sergittos/bedwars/game/shop/tracker/TrackerProduct

**Comment by Sergittos** [comment]
> > Everything should be fixed now
> 
> Error: Class sergittos\bedwars\game\shop\tracker\TrackerProduct contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (sergittos\bedwars\game\shop\Product::canBePurchased) File: plugins/BedWars-master/src/sergittos/bedwars/game/shop/tracker/TrackerProduct

Fixed :)

**Comment by UnknownNull** [comment]
> > > Everything should be fixed now
> > 
> > 
> > Error: Class sergittos\bedwars\game\shop\tracker\TrackerProduct contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (sergittos\bedwars\game\shop\Product::canBePurchased) File: plugins/BedWars-master/src/sergittos/bedwars/game/shop/tracker/TrackerProduct
> 
> Fixed :)

Call to a member function removePlayer() on null" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/item/game/LeaveGameItem" at line 22

**Comment by UnknownNull** [comment]
new bug: The two players are not visible in the map and the game does not recognize them (wdpe is used)

**Comment by UnknownNull** [comment]
and database:
![image](https://github.com/Sergittos/BedWars/assets/91208232/9ad67d25-7801-444f-8c91-02f4b2b706d9)

**Comment by Sergittos** [comment]
> and database: ![image](https://private-user-images.githubusercontent.com/91208232/294599282-9ad67d25-7801-444f-8c91-02f4b2b706d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODc3NjQsIm5iZiI6MTcwNDQ4NzQ2NCwicGF0aCI6Ii85MTIwODIzMi8yOTQ1OTkyODItOWFkNjdkMjUtNzgwMS00NDRmLThjOTEtMDJmNGIyYjcwNmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIwNDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OTM5YmY5Yzc1MGY1NDVhMzAxZWM3NjIwMThiM2NjOTBmZjExMDE4ZWI5NWYzMTgzYzZhZGQzZjM1YTFkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BG1MCPmkhSN8iDq4n3tAptRhDf8SJzcrPtfyliLFqkc)

It doesn't happen to me, perhaps WaterdogPE is causing a conflict here

**Comment by Sergittos** [comment]
Everything fixed in 1.0.1

**Comment by UnknownNull** [comment]
> Everything fixed in 1.0.1

Suggestion: The color and name of some teams should be changed to become famous servers like Bedwars and ready maps!

**Comment by UnknownNull** [comment]
> Everything fixed in 1.0.1

leave game not work (bed)

**Comment by UnknownNull** [comment]
game not start :D

**Comment by UnknownNull** [comment]
bug line 239/254 
src/sergittos/bedwars/listener/GameListener.php

> game not start :D

**Comment by UnknownNull** [comment]
NEW : The item store and upgrades are automatically deleted after the player is not around

**Comment by Sergittos** [comment]
> Suggestion: The color and name of some teams should be changed to become famous servers like Bedwars and ready maps!

Feel free to make another issue explaining this suggestion in more detail

**Comment by Sergittos** [comment]
> NEW : The item store and upgrades are automatically deleted after the player is not around

It doesn't happen to me, can you send a video of the bug?

**Comment by Sergittos** [comment]
> leave game not work (bed)

It works for me

**Comment by UnknownNull** [comment]
> > NEW : The item store and upgrades are automatically deleted after the player is not around
> 
> It doesn't happen to me, can you send a video of the bug?

https://www.mediafire.com/file/3gvbfoj3awl482q/2024-01-06_22-46-58.mp4/file

**Comment by UnknownNull** [comment]
and:
```
2024-01-05 [23:41:35.027] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\entity\projectile\Arrow::getOwner()" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/listener/GameListener" at line 337
--- Stack trace ---
  #0 pmsrc/src/event/RegisteredListener(61): sergittos\bedwars\listener\GameListener->onPickup(object pocketmine\event\entity\EntityItemPickupEvent#248725)
  #1 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityItemPickupEvent#248725)
  #2 pmsrc/src/entity/projectile/Arrow(188): pocketmine\event\Event->call()
  #3 pmsrc/src/player/Player(1249): pocketmine\entity\projectile\Arrow->onCollideWithPlayer(object pocketmine\player\Player#113380)
  #4 pmsrc/src/player/Player(1450): pocketmine\player\Player->checkNearEntities()
  #5 pmsrc/src/world/World(1067): pocketmine\player\Player->onUpdate(int 69748)
  #6 pmsrc/src/world/World(992): pocketmine\world\World->actuallyDoTick(int 69748)
  #7 pmsrc/src/world/WorldManager(351): pocketmine\world\World->doTick(int 69748)
  #8 pmsrc/src/Server(1832): pocketmine\world\WorldManager->tick(int 69748)
  #9 pmsrc/src/Server(1714): pocketmine\Server->tick()
  #10 pmsrc/src/Server(1090): pocketmine\Server->tickProcessor()
  #11 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[51] C:\Users\Administrator\Documents\MV - RL\5.BedWars\, string[59] C:\Users\Administrator\Documents\MV - RL\5.BedWars\plugins\)
  #12 pmsrc/src/PocketMine(364): pocketmine\server()
  #13 pmsrc(11): require(string[95] phar://C:/Users/Administrator/Documents/MV - RL/5.BedWars/PocketMine-MP.phar/src)
```

**Comment by UnknownNull** [comment]
> > > NEW : The item store and upgrades are automatically deleted after the player is not around
> > 
> > 
> > It doesn't happen to me, can you send a video of the bug?
> 
> https://www.mediafire.com/file/3gvbfoj3awl482q/2024-01-06_22-46-58.mp4/file

Defend bed and the nearby bridge of that team will be removed like the item shop...

**Comment by UnknownNull** [comment]
and:
```
2024-01-06 [20:05:07.877] [Server thread/CRITICAL]: DivisionByZeroError: "Division by zero" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/game/generator/Generator" at line 58
--- Stack trace ---
  #0 plugins/BedWars-master/src/sergittos/bedwars/game/generator/presets/TextGenerator(33): sergittos\bedwars\game\generator\Generator->setSpeed(int 0)
  #1 plugins/BedWars-master/src/sergittos/bedwars/game/event/presets/UpgradeGeneratorsTierEvent(32): sergittos\bedwars\game\generator\presets\TextGenerator->setTier(object sergittos\bedwars\game\generator\Tier#222647)
  #2 plugins/BedWars-master/src/sergittos/bedwars/game/event/Event(40): sergittos\bedwars\game\event\presets\UpgradeGeneratorsTierEvent->end()
  #3 plugins/BedWars-master/src/sergittos/bedwars/game/stage/PlayingStage(83): sergittos\bedwars\game\event\Event->hasEnded()
  #4 plugins/BedWars-master/src/sergittos/bedwars/game/GameHeartbeat(26): sergittos\bedwars\game\stage\PlayingStage->tick()
  #5 pmsrc/src/scheduler/TaskHandler(113): sergittos\bedwars\game\GameHeartbeat->onRun()
  #6 pmsrc/src/scheduler/TaskScheduler(137): pocketmine\scheduler\TaskHandler->run()
  #7 pmsrc/src/plugin/PluginManager(533): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 80940)
  #8 pmsrc/src/Server(1825): pocketmine\plugin\PluginManager->tickSchedulers(int 80940)
  #9 pmsrc/src/Server(1714): pocketmine\Server->tick()
  #10 pmsrc/src/Server(1090): pocketmine\Server->tickProcessor()
  #11 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[51] C:\Users\Administrator\Documents\MV - RL\5.BedWars\, string[59] C:\Users\Administrator\Documents\MV - RL\5.BedWars\plugins\)
  #12 pmsrc/src/PocketMine(364): pocketmine\server()
  #13 pmsrc(11): require(string[95] phar://C:/Users/Administrator/Documents/MV - RL/5.BedWars/PocketMine-MP.phar/src)
```

**Comment by Sergittos** [comment]
Everything should be fixed in 1.0.4

**Comment by UnknownNull** [comment]
> Everything should be fixed in 1.0.4

no!
1: https://github.com/Sergittos/BedWars/issues/2#issuecomment-1879794929
2:
```
2024-01-07 [20:03:05.485] [Server thread/CRITICAL]: Error: "Call to a member function getWorld() on null" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/game/team/Team" at line 180
--- Stack trace ---
  #0 plugins/BedWars-master/src/sergittos/bedwars/game/stage/PlayingStage(48): sergittos\bedwars\game\team\Team->addMember(object sergittos\bedwars\session\Session#158764)
  #1 plugins/BedWars-master/src/sergittos/bedwars/game/stage/Stage(18): sergittos\bedwars\game\stage\PlayingStage->onStart()
  #2 plugins/BedWars-master/src/sergittos/bedwars/game/Game(160): sergittos\bedwars\game\stage\Stage->start(object sergittos\bedwars\game\Game#197654)
  #3 plugins/BedWars-master/src/sergittos/bedwars/game/stage/StartingStage(43): sergittos\bedwars\game\Game->setStage(object sergittos\bedwars\game\stage\PlayingStage#131458)
  #4 plugins/BedWars-master/src/sergittos/bedwars/game/GameHeartbeat(26): sergittos\bedwars\game\stage\StartingStage->tick()
  #5 pmsrc/src/scheduler/TaskHandler(113): sergittos\bedwars\game\GameHeartbeat->onRun()
  #6 pmsrc/src/scheduler/TaskScheduler(137): pocketmine\scheduler\TaskHandler->run()
  #7 pmsrc/src/plugin/PluginManager(533): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 11760)
  #8 pmsrc/src/Server(1825): pocketmine\plugin\PluginManager->tickSchedulers(int 11760)
  #9 pmsrc/src/Server(1714): pocketmine\Server->tick()
  #10 pmsrc/src/Server(1090): pocketmine\Server->tickProcessor()
  #11 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[51] C:\Users\Administrator\Documents\MV - RL\5.BedWars\, string[59] C:\Users\Administrator\Documents\MV - RL\5.BedWars\plugins\)
  #12 pmsrc/src/PocketMine(364): pocketmine\server()
  #13 pmsrc(11): require(string[95] phar://C:/Users/Administrator/Documents/MV - RL/5.BedWars/PocketMine-MP.phar/src)
```

**Comment by UnknownNull** [comment]
wins not save. after restart server reseted data...

**Comment by Sergittos** [comment]
> wins not save. after restart server reseted data...

What provider are you using?

**Comment by UnknownNull** [comment]
> > wins not save. after restart server reseted data...
> 
> What provider are you using?

mysql

**Comment by UnknownNull** [comment]
The orange bed is not destroyed

**Comment by Sergittos** [comment]
> The orange bed is not destroyed

That's probably a setup error, team colors have nothing to do with the gameplay

**Comment by UnknownNull** [comment]
```
2024-01-07 [20:55:09.023] [Server thread/CRITICAL]: Error: "Call to a member function getDyeColor() on null" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/game/shop/item/category/BlocksCategory" at line 25
--- Stack trace ---
  #0 plugins/BedWars-master/src/sergittos/bedwars/form/shop/CategoryForm(32): sergittos\bedwars\game\shop\item\category\BlocksCategory->getProducts(object sergittos\bedwars\session\Session#240186)
  #1 C:/Users/Administrator/Documents/MV - RL/5.BedWars/virions/EasyUI-master/src/EasyUI/Form(27): sergittos\bedwars\form\shop\CategoryForm->onCreation()
  #2 C:/Users/Administrator/Documents/MV - RL/5.BedWars/virions/EasyUI-master/src/EasyUI/variant/SimpleForm(31): EasyUI\Form->__construct(string[6] Blocks)
```

**Comment by UnknownNull** [comment]
> > The orange bed is not destroyed
> 
> That's probably a setup error, team colors have nothing to do with the gameplay

i test this but... om i test again....

**Comment by UnknownNull** [comment]
In 2-person and squad modes, Iron Forge only gives items to one of the players inside Iron Forge.

**Comment by Sergittos** [comment]
Or maybe a plugin is causing a conflict here

**Comment by UnknownNull** [comment]
2024-01-10 [15:21:36.400] [Server thread/CRITICAL]: Error: "Call to a member function getUpgrades() on null" (EXCEPTION) in "plugins/BedWars-master/src/sergittos/bedwars/game/shop/upgrades/category/UpgradesCategory" at line 24

**Comment by UnknownNull** [comment]
> Or maybe a plugin is causing a conflict here

not fixed
![image](https://github.com/Sergittos/BedWars/assets/91208232/f3d04a09-61bf-4157-b7c7-875651633679)

**Comment by UnknownNull** [comment]
There is no problem with any plugin. This problem is either from `pocketmine-mp` or from `waterdogpe`.

**Comment by UnknownNull** [comment]
Realized that the problem is from `pocketmine`

**Comment by UnknownNull** [comment]
@Sergittos 
What should we do so that the shops, upgrades and blocks placed near the team's base are not deleted?

This happens when the player is keeled or waded and is away from his base....
