### ISSUE TITLE
getName() on null

### ISSUE THREAD

**Issue by AraaCuteUwU** [Sergittos/BedWars#25]
**To Reproduce**
Join random into the arena

**Additional context**
[Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "plugins/BedWars/src/sergittos/bedwars/listener/GameListener" at line 215
--- Stack trace ---
  #0 pmsrc/src/event/RegisteredListener(61): sergittos\bedwars\listener\GameListener->onMove(object pocketmine\event\player\PlayerMoveEvent#189146)
  #1 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#189146)
  #2 pmsrc/src/player/Player(1338): pocketmine\event\Event->call()
  #3 pmsrc/src/player/Player(1431): pocketmine\player\Player->processMostRecentMovements()
  #4 pmsrc/src/world/World(997): pocketmine\player\Player->onUpdate(int 19848)
  #5 pmsrc/src/world/World(922): pocketmine\world\World->actuallyDoTick(int 19848)
  #6 pmsrc/src/world/WorldManager(351): pocketmine\world\World->doTick(int 19848)
  #7 pmsrc/src/Server(1805): pocketmine\world\WorldManager->tick(int 19848)
  #8 pmsrc/src/Server(1687): pocketmine\Server->tick()
  #9 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
  #10 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string
[68] C:\Users\LENOVO\OneDrive\Documents\project\AraaNetwork\bedwars-test\, string[76] C:\Users\LENOVO\OneDrive\Documents\project\AraaNetwork\bedwars-test\plugins\)
  #11 pmsrc/src/PocketMine(364): pocketmine\server()
  #12 pmsrc(11): require(string[112] phar://C:/Users/LENOVO/OneDrive/Documents/project/AraaNetwork/bedwars-test/Pocke)
--- End of exception information ---

**Comment by Sergittos** [comment]
Can you attach a video reproducing this bug?

**Comment by UnknownNull** [comment]
> **To Reproduce** Join random into the arena
> 
> **Additional context** [Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "plugins/BedWars/src/sergittos/bedwars/listener/GameListener" at line 215 --- Stack trace --- #0 pmsrc/src/event/RegisteredListener(61): sergittos\bedwars\listener\GameListener->onMove(object pocketmine\event\player\PlayerMoveEvent#189146) #1 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#189146) #2 pmsrc/src/player/Player(1338): pocketmine\event\Event->call() #3 pmsrc/src/player/Player(1431): pocketmine\player\Player->processMostRecentMovements() #4 pmsrc/src/world/World(997): pocketmine\player\Player->onUpdate(int 19848) #5 pmsrc/src/world/World(922): pocketmine\world\World->actuallyDoTick(int 19848) #6 pmsrc/src/world/WorldManager(351): pocketmine\world\World->doTick(int 19848) #7 pmsrc/src/Server(1805): pocketmine\world\WorldManager->tick(int 19848) #8 pmsrc/src/Server(1687): pocketmine\Server->tick() #9 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor() #10 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string [68] C:\Users\LENOVO\OneDrive\Documents\project\AraaNetwork\bedwars-test, string[76] C:\Users\LENOVO\OneDrive\Documents\project\AraaNetwork\bedwars-test\plugins) #11 pmsrc/src/PocketMine(364): pocketmine\server() #12 pmsrc(11): require(string[112] phar://C:/Users/LENOVO/OneDrive/Documents/project/AraaNetwork/bedwars-test/Pocke) --- End of exception information ---

This bug should be from `maps.json`.  If you can send it and if you can't check that you haven't changed the names of the teams

**Comment by Sergittos** [comment]
Closed due to inactivity
