### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by Aryanxxpro1234** [Sergittos/BedWars#26]
When the game isn't full, countdown doesn't start. Please make the countdown start when the game isn't full and the game starts.

![IMG_20240121_215158_820](https://github.com/Sergittos/BedWars/assets/128404227/a20bd361-fc77-4002-8901-0ad38baeb720)

**Comment by Sergittos** [comment]
The game only starts if the half lobby is full (4 players in your case).

Anyways, I have pending a new queueing system, it will be probably ready in a few weeks.

**Comment by UnknownNull** [comment]
> When the game isn't full, countdown doesn't start. Please make the countdown start when the game isn't full and the game starts.
> 
> ![IMG_20240121_215158_820](https://private-user-images.githubusercontent.com/128404227/298403114-a20bd361-fc77-4002-8901-0ad38baeb720.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NjE3NjcsIm5iZiI6MTcwNTg2MTQ2NywicGF0aCI6Ii8xMjg0MDQyMjcvMjk4NDAzMTE0LWEyMGJkMzYxLWZjNzctNDAwMi04OTAxLTBhZDM4YmFlYjcyMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQxODI0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDUyNzk0OWVlZjJlNjZmODliNzM5Yzg4YWZmZWQzZjU4NWI4NDJiNmEzMmYyNzIwZmY1OGIxOGU0ZWNkNjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I8eVe0Wrzonm9K8YelbuBtCpYXomuJT7V2351adCjEc)

At least half of the maximum total number must be present for the counter to start

**Comment by UnknownNull** [comment]
It was answered earlier than me🙄

**Comment by Sergittos** [comment]
> It was answered earlier than me🙄

:)
