### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by ClydeplayzYT590** [Sergittos/BedWars#3]
The server always crashes in the middle of a game so here's some crashdumps

[archive-2024-01-07T214851+0100.tar.gz](https://github.com/Sergittos/BedWars/files/13854905/archive-2024-01-07T214851%2B0100.tar.gz)

**Comment by Sergittos** [comment]
Are you using the last version?

**Comment by ClydeplayzYT590** [comment]
> Are you using the last version?

No, but I'll check it out if the crash still occurs

**Comment by Sergittos** [comment]
@ClydeplayzYT590 any updates?

**Comment by ClydeplayzYT590** [comment]
Fixed I guess
