### ISSUE TITLE
Server Crash when teleporting

### ISSUE THREAD

**Issue by ClydeplayzYT590** [Sergittos/BedWars#35]
**Describe the bug**
The server crashes if a player (which is not playing the game) teleports to a player playing the game, the server will crash (Collected from MixedMC Games)

**To Reproduce**
1. Join the server and play BedWars
2. Leave the game and teleport to a player playing the game

**Expected behavior**
Teleporting should have no issues

**Additional context**
Crash dump:
[Wed_Feb_14-13.43.52-UTC_2024.log](https://github.com/Sergittos/BedWars/files/14280765/Wed_Feb_14-13.43.52-UTC_2024.log)

**Comment by xwertxy** [comment]
This is debugged, reproduced by me. I think `$team->getName()` is returning null.

**Comment by Sergittos** [comment]
Fixed in the last commit, thanks!
