### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by lilfantax** [Sergittos/BedWars#45]
BCrash occurred while handling a packet from session: lilfantax1995(B(B
[19:45:13.282] (B[Server thread/CRITICAL]: (BError: "Class "EasyUI\variant\SimpleForm" not found" (EXCEPTION) in "plugins/BedWars-94ebe15fe9333fc03a7faa81c26c4b80d1f71542/src/sergittos/bedwars/form/SimpleForm" at line 15

--- Stack trace ---  #18 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()  #0 pmsrc/src/thread/ThreadSafeClassLoader(133): include()
  #1 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[33] sergittos\bedwars\form\SimpleForm)
  #2 plugins/BedWars-94ebe15fe9333fc03a7faa81c26c4b80d1f71542/src/sergittos/bedwars/form/setup/BedwarsForm(11): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[33] sergittos\bedwars\form\SimpleForm)
  #3 pmsrc/src/thread/ThreadSafeClassLoader(133): include(string[143] /var/lib/pufferpanel/servers/f0c5e9f2/plugins/BedWars-94ebe15fe9333fc03a7faa81c2)
  #4 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[40] sergittos\bedwars\form\setup\BedwarsForm)
  #5 plugins/BedWars-94ebe15fe9333fc03a7faa81c26c4b80d1f71542/src/sergittos/bedwars/command/BedWarsCommand(39): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[40] sergittos\bedwars\form\setup\BedwarsForm)
  #6 pmsrc/src/command/SimpleCommandMap(212): sergittos\bedwars\command\BedWarsCommand->execute(object pocketmine\player\Player#77446, string[7] bedwars, array[0])
  #7 pmsrc/src/Server(1431): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#77446, string[7] bedwars)
  #8 pmsrc/src/player/Player(1516): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#77446, string[7] bedwars)
  #9 pmsrc/src/network/mcpe/handler/InGamePacketHandler(819): pocketmine\player\Player->chat(string[8] /bedwars)
  #10 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#160431)
  #11 pmsrc/src/network/mcpe/NetworkSession(468): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#158365)
  #12 pmsrc/src/network/mcpe/NetworkSession(406): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#160431, string[30] M./bedwars..G......CXE..k....L)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[75] .....OJM)O,*fx..c..i.....|....20..L`dp.o.@....C.s.m7.^....`qF&.}L ....{....)
  #14 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[84] .:.0..+..../...N..^.#\...q...sMD.........}...*....(..<..{.G.,$M.~~...u.bW......X)
  #15 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#205148)
  #16 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()

  #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #20 pmsrc/src/Server(1696): pocketmine\snooze\SleeperHandler->sleepUntil(float 1718480713.2958)
  #21 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #22 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#2, object pocketmine\utils\MainLogger#6, string[38] /var/lib/pufferpanel/servers/f0c5e9f2/, string[46] /var/lib/pufferpanel/servers/f0c5e9f2/plugins/)
  #23 pmsrc/src/PocketMine(378): pocketmine\server()
  #24 /var/lib/pufferpanel/servers/f0c5e9f2/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPec1Ayf.tar/src/PocketMine.php)
--- End of exception information ---(B(B

**Comment by Sergittos** [comment]
You have to download the plugin from [Poggit](https://poggit.pmmp.io/p/BedwarsPM/1.0.9)
